### ISSUE TITLE
Pruning eliminates code objects without corresponding events from recorded AppMaps.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#43]

**Comment by lachrist** [comment]
I'm puzzled. That is what pruning is supposed to do. Note that pruning is now disabled by default.

**Comment by ptrdvrk** [comment]
This is a feature request @lachrist . Pruning should be enabled by default and eliminate all code objects from the appmap that don't have corresponding events.

**Comment by ptrdvrk** [comment]
Example: [Test10.appmap.txt](https://github.com/applandinc/appmap-agent-js/files/7515753/Test10.appmap.txt)

Only the `login` class in this AppMap has corresponding events recorded, the other classes should not be present.

![image](https://user-images.githubusercontent.com/42008542/141189542-e9d127fe-8ca5-4eb1-a431-654e1ddb8798.png)

**Comment by lachrist** [comment]
This should be fixed in: b14e965baf1645762c9bd16a57c6be655274ec98

**Comment by ptrdvrk** [comment]
@lachrist can you please review this appmap? I still see sources in the class map without any object/events. Is the pruning on by default?
[Test6.appmap.json.txt](https://github.com/applandinc/appmap-agent-js/files/7529028/Test6.appmap.json.txt)

**Comment by lachrist** [comment]
Yes pruning is on by default but it acts only on functions. Should I also remove classes which do not contain called functions? Sorry I misunderstood pruning :|

**Comment by ptrdvrk** [comment]
Yes please, and similarly all "packages" that don't contain any classes that contain called functions.

**Comment by lachrist** [comment]
Done in: 23c2207041bc84af348c3fa4feb5d531243d2a8b

**Comment by ptrdvrk** [comment]
Looking good now, thank you!
